### ISSUE TITLE
class-monkey breaks play projects

### ISSUE THREAD

**Issue by jeantil** [fommil/class-monkey#26]
Hi, 

first of all, thanks for class-monkey, it is a huge time saver. At least as long as I don't need to run a play project. 

when I try to run a play project I get: 
```
[play-scala-seed] $ run

sbt appears to be exiting abnormally.
  The log file for this session is at /var/folders/gt/c0_8ryzj2m7fwmf07t68z0940000gn/T/sbt8586955094154742404.log
java.lang.ClassCircularityError: org/slf4j/LoggerFactory
	at org.slf4j.bridge.SLF4JBridgeHandler.getSLF4JLogger(SLF4JBridgeHandler.java:202)
	at org.slf4j.bridge.SLF4JBridgeHandler.publish(SLF4JBridgeHandler.java:293)
	at java.util.logging.Logger.log(Logger.java:738)
	at java.util.logging.Logger.doLog(Logger.java:765)
	at java.util.logging.Logger.log(Logger.java:788)
	at java.util.logging.Logger.finest(Logger.java:1542)
	at fommil.URLClassPath$ArchiveResourceProvider.get(URLClassPath.java:447)
	at fommil.URLClassPath.getResource(URLClassPath.java:190)
	at fommil.URLClassPath.getResource(URLClassPath.java:159)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:365)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sbt.State$.handleException(State.scala:249)
	at sbt.State$$anon$1.handleError(State.scala:212)
	at sbt.MainLoop$.next(MainLoop.scala:99)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:109)
	at sbt.xMain.run(Main.scala:38)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: java.lang.ClassCircularityError: org/slf4j/LoggerFactory
```

The above error was obtained by running the following command (and accepting all the proposed default values)
```
> sbt new playframework/play-scala-seed.g8
This template generates a Play Scala project

name [play-scala-seed]:
organization [com.example]:
scala_version [2.11.11]:
play_version [2.5.14]:
scalatestplusplay_version [2.0.0]:

Template applied in ./play-scala-seed
```

Commenting the javaagent in $PWD/.sbtopts the project behaves as expected : 
```
$> sbt
[play-scala-seed] $ run
[info] Loading global plugins from /Users/jean/.sbt/0.13/plugins
[info] Loading project definition from /Users/jean/dev/lizeo/src/play-scala-seed/project
[info] Set current project to play-scala-seed (in build file:/Users/jean/dev/lizeo/src/play-scala-seed/)
[play-scala-seed] $ run

--- (Running the application, auto-reloading is enabled) ---
...
```

maybe class-monkey's classloader implementation is slightly too simple :)

is there any chance that this https://stackoverflow.com/questions/30565831/urlclassloader-memory-leak-java which lead me to https://github.com/mjiderhamn/classloader-leak-prevention is related to sbt's problems? it looks like there are multiple traps leading to memory leaks when manipulating class laoders...

**Comment by fommil** [comment]
huh, interesting. If you submit a failing test and fix, I'd be happy to release a new binary. I'm tempted to suggest that Play are doing something crazy.

Try starting your app / tests by loading SLF4J before the play framework.

**Comment by fommil** [comment]
the other thing you could do is to add slfj4 jars to the bootclasspath. `class-monkey` cannot change the boot classloader, only the system classloader.

**Comment by fommil** [comment]
another workaround would be to feature flag all the log statements in `class-monkey`, e.g. by reading a system property.

**Comment by jeantil** [comment]
As far as I know there is no way for the enduser to load anything before the framework starts :( deleting all user code in the sample results in the same error which points to a conflict with something in play. most likely in the play sbt plugin.

**Comment by fommil** [comment]
@dwijnand is there any way to load any code in sbt before any plugins load?

**Comment by fommil** [comment]
@jeantil how about `fork := true` or does that not work in play?

**Comment by jeantil** [comment]
> add slfj4 jars to the bootclasspath
while doable as an experiment it can't be done easily in a general way, slf4j is brought as a dependency of the project and the jar is part of the sbt managed dependencies. sure I can add a 
`-Xbootclasspath` pointing to the right version in my ivy repo but that would be fairly fragile :(

>to feature flag all the log statements 
an option could be to have class-monkey rely on `java.logging` which is internal to the jdk instead of slf4j ? this would limit external dependencies which could lead to class loading conflicts ... 
Then again I am not sure how the dependencies of an agent are loaded and if having class-monkey depend on slf4j is actually the issue here.

> `fork := true `
```
play-scala-seed] $ set fork:=true
[info] Defining *:fork
[info] The new value will be used by *:runner, compile:run::runner
[info] Reapplying settings...
[info] Set current project to play-scala-seed (in build file:/Users/jean/dev/lizeo/src/play-scala-seed/)
[play-scala-seed] $ run

sbt appears to be exiting abnormally.
  The log file for this session is at /var/folders/gt/c0_8ryzj2m7fwmf07t68z0940000gn/T/sbt4219512467246547953.log
java.lang.ClassCircularityError: org/slf4j/LoggerFactory
	at org.slf4j.bridge.SLF4JBridgeHandler.getSLF4JLogger(SLF4JBridgeHandler.java:202)
	at org.slf4j.bridge.SLF4JBridgeHandler.publish(SLF4JBridgeHandler.java:293)
	at java.util.logging.Logger.log(Logger.java:738)
	at java.util.logging.Logger.doLog(Logger.java:765)
	at java.util.logging.Logger.log(Logger.java:788)
	at java.util.logging.Logger.finest(Logger.java:1542)
	at fommil.URLClassPath$ArchiveResourceProvider.get(URLClassPath.java:447)
	at fommil.URLClassPath.getResource(URLClassPath.java:190)
	at fommil.URLClassPath.getResource(URLClassPath.java:159)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:365)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sbt.State$.handleException(State.scala:249)
	at sbt.State$$anon$1.handleError(State.scala:212)
	at sbt.MainLoop$.next(MainLoop.scala:99)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:109)
	at sbt.xMain.run(Main.scala:38)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: java.lang.ClassCircularityError: org/slf4j/LoggerFactory
```

**Comment by fommil** [comment]
@jeantil quick workaround for you is to clone this repo, delete all references to logging, and build your own jar with `sbt assembly`.

**Comment by jeantil** [comment]
Indeed I must have been tired
will try that tomorrow morning

Thanks !

**Comment by dwijnand** [comment]
@fommil According to http://www.scala-sbt.org/0.13/docs/Setting-Initialization.html you can do things before project-level plugins.

**Comment by jeantil** [comment]
I had a look into creating a version of the jar with all logging statements removed. Upon reading the source code I was doubtful it would help. 
The production code itself uses only java util logging which is distributed in the jdk, slf4j is only added as a test dependency and it is not in the final assembly.

I went ahead and built an assembly which didn't use logging at all and it worked just fine. 

Digging a bit, play has a `+-org.slf4j:jul-to-slf4j:1.7.21` dependency 
I assume that because the agent uses jul this dependency is summoned "early" and the loading fails :/

I had a quick look at the jdk's URLClassPath implementation and it doesn't use java.logging.util either...

**Comment by fommil** [comment]
yeah, that's what I seen in the stacktrace. The logging was useful for me to diagnose what was happening, but maybe we should just use system properties and stderr.
