### ISSUE TITLE
class-monkey breaks sbt<->intellij sync

### ISSUE THREAD

**Issue by jeantil** [fommil/class-monkey#27]
Enabling the agent in a project's `.sbtopts` file then importing or refreshing that project in intellij yields the following error : 
```
Error:Error while importing SBT project:<br/>...<br/><pre>at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
at xsbt.boot.Using$.withResource(Using.scala:10)

at xsbt.boot.Using$.apply(Using.scala:9)
at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
at xsbt.boot.Locks$.apply0(Locks.scala:31)
at xsbt.boot.Locks$.apply(Locks.scala:28)
at xsbt.boot.Launch.locked(Launch.scala:238)
at xsbt.boot.Launch.app(Launch.scala:147)
at xsbt.boot.Launch.app(Launch.scala:145)
at xsbt.boot.Launch$.run(Launch.scala:102)
at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
at xsbt.boot.Launch$.launch(Launch.scala:117)
at xsbt.boot.Launch$.apply(Launch.scala:18)
at xsbt.boot.Boot$.runImpl(Boot.scala:41)
at xsbt.boot.Boot$.main(Boot.scala:17)
at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: java.lang.NoSuchMethodError: sun.misc.URLClassPath.<init>([Ljava/net/URL;Ljava/security/AccessControlContext;)V</pre><br/>See complete log in <a href="file:/Users/jean/Library/Logs/IntelliJIdea2017.2/sbt.last.log">file:/Users/jean/Library/Logs/IntelliJIdea2017.2/sbt.last.log</a>
``` 
disabling the agent immediatly restores sync

**Comment by fommil** [comment]
you're using an old version with java 8

**Comment by jeantil** [comment]
sorry about that, the project was indeed on 1.8.0_91 upgrading to 1.8.0_121 solved this issue.
